runner:
  total_steps: 100000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 200
  eval_step: 1000
  save_step: 1000
  max_keep: 1
  eval_dataloaders: 
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4 #1.0e-2

downstream_expert: 
  datarc:
    h5_dir: /gscratch/tial/data/LibriTTS-R/LibriTTS_R
    meta_data: /gscratch/tial/kpever/workspace/s3prl/s3prl/downstream/energy/split
    sr: 16000
    num_workers: 8
    train_batch_size: 32
    eval_batch_size: 1
    glottal_kwargs:
      return_glottal: True

  modelrc:
    projector_dim: 256
    select: FrameLevel